# baseurl is the root
baseurl: '/'

# Files/Folders to exclude from the final output
exclude:
  - .sass-cache
  - CNAME
  - config.rb
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - node_modules
  - .jekyll-cache
  - package.json
  - package-lock.json
  - webpack.config.babel.js
  - vue.config.js

compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: [local]
  blanklines: true
  profile: false
  startings: []

sass:
  sass_dir: css

permalink: none

highlighter: rouge
markdown: kramdown
